<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <nullable>enable</nullable>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.0</FileVersion>
    <Version>1.1.0</Version>
    <Description>Poker hand formation checker with both string only interface and typed interface.</Description>
    <PackageReleaseNotes>Moved to .NET 8.0.</PackageReleaseNotes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Copyright>Anders Hesselbom</Copyright>
    <Authors>Anders Hesselbom</Authors>
    <Company>Anders HesselbomAnders Hesselbom</Company>
    <PackageId>PokerFormationChecker</PackageId>
    <PackageProjectUrl>https://github.com/Anders-H/GenericPokerFormationChecker</PackageProjectUrl>
    <PackageIcon>poker.png</PackageIcon>
    <RepositoryUrl>https://github.com/Anders-H/GenericPokerFormationChecker</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\poker.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GameStyles\" />
  </ItemGroup>

</Project>